### ISSUE TITLE
Create activity with Image

### ISSUE THREAD

**Issue by phamNam0** [sweIhm/sweiproject-tg2a-2#2]
As a user i want to create a new activity to share my projects with other students of MUAS or CAL POLY with images.

Acceptance Criteria:
 

- I can create a new activity which can contain text, pictures and videos.
- The user stays anonymous
- I can mark his project with any number of tags
- I have to name the activity, add a catagory and add a department/college

**Comment by Akavith** [comment]
ready for review

**Comment by Nilsilino** [comment]
User Issue updatet:  no Videos in Acceptance Criteria

**Comment by Nilsilino** [comment]
Review done
